# Generated by Django 4.0.3 on 2022-03-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teacher_department_alter_teacher_load_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teacher',
        ),
    ]
