# Generated by Django 4.0.3 on 2022-05-23 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_subject_taken_hour_subject_taken_lab_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('time', models.CharField(max_length=200)),
                ('classroom', models.CharField(max_length=200)),
                ('is_lecture', models.BooleanField()),
                ('is_practice', models.BooleanField()),
                ('group_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.groupsubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
    ]
