# Generated by Django 4.0.3 on 2022-05-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='week_day',
            field=models.CharField(max_length=20),
        ),
    ]
