# Generated by Django 4.0.3 on 2022-03-17 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_teacher_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('credits', models.IntegerField()),
                ('lecture_count', models.IntegerField(null=True)),
                ('practice_count', models.IntegerField(null=True)),
                ('office_count', models.IntegerField(null=True)),
                ('lab_count', models.IntegerField(null=True)),
                ('lecture_hour', models.IntegerField(null=True)),
                ('practice_hour', models.IntegerField(null=True)),
                ('office_hour', models.IntegerField(null=True)),
                ('lab_cout', models.IntegerField(null=True)),
                ('total_hour', models.IntegerField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department')),
                ('teacher', models.ManyToManyField(to='api.teacher')),
            ],
            options={
                'db_table': 'subject',
            },
        ),
    ]
