# Generated by Django 4.0.3 on 2022-05-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_schedule_is_lecture_alter_schedule_is_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='is_lecture',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_practice',
            field=models.BooleanField(),
        ),
    ]
