# Generated by Django 4.0.3 on 2022-03-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_subject_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(related_name='subjects', to='api.teacher'),
        ),
    ]
