# Generated by Django 4.0.3 on 2022-03-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='excel_column_index',
            field=models.IntegerField(null=True),
        ),
    ]
