# Generated by Django 4.0.3 on 2022-03-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_teacher_subject_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('course', models.IntegerField()),
                ('number_of_students', models.IntegerField()),
            ],
            options={
                'db_table': 'group',
            },
        ),
    ]
