# Generated by Django 4.0.3 on 2022-03-21 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimester', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
            ],
            options={
                'db_table': 'group_subject',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='groups',
            field=models.ManyToManyField(related_name='subjects', through='api.GroupSubject', to='api.group'),
        ),
        migrations.AddField(
            model_name='groupsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject'),
        ),
    ]
