# Generated by Django 4.0.3 on 2022-03-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_groupsubject_subject_groups_groupsubject_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupsubject',
            unique_together={('subject', 'group')},
        ),
    ]
