# Generated by Django 4.0.3 on 2022-03-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_groupsubject_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='row_index',
            field=models.IntegerField(null=True),
        ),
    ]
