# Generated by Django 4.0.3 on 2022-03-21 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_subject_row_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsubject',
            name='group',
            field=models.ForeignKey(db_column='group_name', on_delete=django.db.models.deletion.CASCADE, to='api.group'),
        ),
    ]
