# Generated by Django 4.0.3 on 2022-03-23 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_groupsubject_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='total_hours',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lecture', models.BooleanField()),
                ('is_lab', models.BooleanField()),
                ('group_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.groupsubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
            options={
                'db_table': 'workload',
            },
        ),
    ]
