# Generated by Django 4.0.3 on 2022-03-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_teacher_total_hours_workload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='lab_cout',
            new_name='lab_hour',
        ),
    ]
