# Generated by Django 4.0.3 on 2022-03-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_subject_lab_count_alter_subject_lab_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='total_hours',
            field=models.IntegerField(default=0),
        ),
    ]
