# Generated by Django 4.0.3 on 2022-03-23 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_total_hours_teacher_total_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workload',
            name='group_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.groupsubject'),
        ),
    ]
