# Generated by Django 4.0.3 on 2022-03-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_workload_group_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='workload',
            name='is_prac',
            field=models.BooleanField(default=True),
        ),
    ]
