# Generated by Django 4.0.3 on 2022-03-29 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_workload_is_prac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workload',
            old_name='is_prac',
            new_name='is_practice',
        ),
    ]
