# Generated by Django 4.0.3 on 2022-05-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_is_prac_workload_is_practice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='row_index',
            new_name='excel_row_index',
        ),
        migrations.AddField(
            model_name='teacher',
            name='kpi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
