# Generated by Django 4.0.3 on 2022-05-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacher_one_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='excel_column_index',
        ),
    ]
