# Generated by Django 4.0.3 on 2022-06-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_teacher_excel_column_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email_verify',
            field=models.BooleanField(default=False),
        ),
    ]
