# Generated by Django 4.0.3 on 2022-06-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_teacher_email_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='email_verify',
        ),
    ]
